music_directory     "/home/pi/audio"
playlist_directory  "/var/lib/mpd/playlists"
db_file             "/var/lib/mpd/tag_cache"
state_file          "/var/lib/mpd/state"
sticker_file        "/var/lib/mpd/sticker.sql"

bind_to_address     "localhost"
port                "6600"

auto_update         "yes"

input {
    plugin "curl"
}

audio_output {
    type        "alsa"
    name        "Radio HiFiBerry"
    device      "radio_mono"
    mixer_type  "software"
}